apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::007670671403:role/eksctl-roboshop1-nodegroup-spot-NodeInstanceRole-xdqsLmEgHUyZ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::007670671403:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::007670671403:user/ramesh
      username: ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::007670671403:user/devops-trainee
      username: devops-trainee
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-16T16:15:57Z"
  name: aws-auth
  namespace: kube-system