apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::007670671403:role/eksctl-roboshop1-nodegroup-spot-NodeInstanceRole-xdqsLmEgHUyZ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::007670671403:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-16T16:15:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1319"
  uid: 192ec6c6-8bc1-4989-83dc-a5f99771c3b7